### PR TITLE
Added optional "ignore patterns" to STATICFILES_DIRS.

### PR DESCRIPTION
**Pull request by dbinit**
Hello,

I have found the optional prefix in STATICFILES_DIRS to be very powerful except I needed it to exclude certain subdirectories and files during "collectstatic".

Seeing as there is a command line option to ignore certain file patterns, I thought it would make sense to expose that option in STATICFILES_DIRS so that it could be restricted to an individual root rather than be global.

I've added documentation as well as tests, though you'll have to forgive me for not actually running the tests. I haven't taken the time to figure out how to set up the test environment yet. It looks like I need to do some reading on tox and jenkins.

Let me know if it needs work. Thanks!

### CODE REVIEW

**Comment by dbinit** [comment]
Ok, I figured out that I just had to install tox and run it.

My new tests are now passing (had them in wrong place at first). Some other tests are failing in Django 1.2.x, but they look unrelated. Maybe I don't have my environment set up right.

**Comment by jezdez** [comment]
Hm, I'm not a big fan of adding even more meaning to the `STATICFILES_DIRS` setting, to be honest, it's one thing to look for a two-item tuple for handling prefixes, but having a third way which is only distinguishable by being an list/tuple or not, is a too ambiguous API.

That said, let's look for a different way. I can see a few other ways of implementing this:

a) add a global `STATICFILES_IGNORE_PATTERNS` that you can use to specify paths to ignore when running collectstatic. It would be analogous to the `--ignore` option of collectstatic and also passed to the `list` methods of the finders.

b) extend/subclass the `FileSystemFinder` finder to be able to easily extend the list of path patterns to ignore. That could be later (in your code) be used for specifying an own setting

**Comment by dbinit** [comment]
Yes, I agree it is ambiguous. I had tried a couple other approaches, but they were worse. :)

The problem with a global setting is that I need to be able to exclude files from a single specific root without affecting the others.

Maybe if STATICFILES_IGNORE_PATTERNS could also specify an optional root, it might work, e.g.:

``` python
STATICFILES_IGNORE_PATTERNS = (
    'tests',
    ('/home/html/static', '*.md'),
)
```

What do you think?

**Comment by jezdez** [comment]
Yeah, that'd work for me.

**Comment by jezdez** [comment]
Actually, now that think about it, why not do this instead:

```
STATICFILES_IGNORE_PATHS = (
    'tests',
    '/home/html/static/*.md',
)
```

.. where each entry can be an absolute or relative path, with glob path extensions.

**Comment by dbinit** [comment]
All tests pass. Let me know what you think.

Thanks!

**Comment by dbinit** [comment]
I made one last tweak to make patterns that are relative to a prefix work.

**Comment by raianul** [comment]
@jezdez I am using in my `settings.py` - `STATICFILES_IGNORE_PATHS`, but its not working.

My Django version is 1.6, and I am using `django.contrib.staticfiles`, instead of that the `-i` is working from the command line.

**Pull request closed without merging**
