### PR TITLE
Fixed issue #12

### PR DESCRIPTION
**Pull request by zyegfryed**
Hi Janis,
I finally tackled this one. More difficult than i supposed in first thought.
I added another test and one file to test relative post-processing.
I also fixed the styles css import URL, since it was broken.
Have a good review.
Regards,

### CODE REVIEW

**Comment by jezdez** [comment]
Great, I had to modify a few things (since `base_url` isn't available in all kinds of storage backends) but the committed change should do the trick, mind checking it out?

**Comment by jezdez** [comment]
Eh, the commit is fd33bf928a1ce0df15cc4b123af904656f315211

**Comment by zyegfryed** [comment]
I've updated the patch with another commit to fix a true-positive broken tests.
Mind checking it out ?

**Comment by zyegfryed** [comment]
I've found an issue on one of my server with the last patch.
I'll tackle it and provide another patch.
Thanks for your patience.

**Pull request merged**
